
language: android
jdk:
- oraclejdk8
sudo: required

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- gem install bundler
- cd android/
- bundle install
- gem update --system

script:
- git clone https://github.com/flutter/flutter.git -b stable
- ./flutter/bin/flutter doctor
- pwd
- cd ..
- flutter build appbundle
- cd android/fastlane
- bundle exec fastlane android distribute


