jobs:
  include:
    - stage: test
      language: dart
      dist: xenial
      addons:
        apt:
          packages:
            - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache
    - stage: build
      script:
      - git clone https://github.com/flutter/flutter.git -b stable
      - ./flutter/bin/flutter build appbundle
    - stage: deploy
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      jdk: oraclejdk8
      sudo: false

      android:
        components:
        - tools
        - platform-tools
      before_script:
      - gem install bundler
      - cd android/
      - touch $HOME/.android/repositories.cfg
      - yes | sdkmanager --update
      - yes | sdkmanager "platforms;android-29"
      - yes | sdkmanager "build-tools;29.0.2"
      - bundle install
      - gem update --system

      script:
      - git clone https://github.com/flutter/flutter.git -b stable
      - ./flutter/bin/flutter build appbundle
      - cd fastlane
      - bundle exec fastlane android distribute

stages:
  - test
  - name: build
    if: NOT branch = "master" AND type = pull_request
  - name: deploy
    if: branch = "master"

