# Flutter build
variables:
  projectDirectory: 'swipe_swap'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: Hey24sheep.flutter.flutter-install.FlutterInstall
      inputs:
        channel: 'stable'
        version: 'latest'

    - task: Hey24sheep.flutter.flutter-build.FlutterBuild
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: key.jks
        apksignerKeystorePassword: $(keypassword)
        apksignerKeyPassword: $(keypassword)
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1