# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "New iOS build for testing on master branch for swipe n swap. Lit"
    lane :distribute do
        firebase_app_distribution(
            app: "1:496887165023:ios:b55e5cbf9178ec44b92bea",
            testers: "rishi.rkhan@gmail.com",
            release_notes: "Initial test version of the app",
            ipa_path: "./build/ios/ipa/swipe_swap.ipa"
        )
    end
end
