# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

full_apk_path = sh "cd .. && cd .. && cd build/app/outputs/flutter-apk && echo -n $(pwd)/app-debug.apk"

platform :android do
    desc "Swipe and Swap Latest build for testing"
    lane :distribute do
        build_android_app(task: "assembleDebug") # build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:496887165023:android:f33867052d662545b92bea",
            apk_path: "#{full_apk_path}",
            groups: "the-og-crew",
            release_notes: "Test out the latest version of the mobile app currently in development by Jon and Rishi"
        )

    end
end

# default_platform(:android)
#
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
